FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY . .

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /client ./cmd/client

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/
COPY --from=builder /client .
COPY configs/client.yaml ./configs/

# Create a directory to store the configuration files
RUN mkdir -p /root/configs

CMD ["./client"]