# Client Configuration
CLIENT_SERVER_ADDRESS="localhost:8080"
CLIENT_CONNECT_TIMEOUT="5s"
CLIENT_READ_TIMEOUT="5s"
CLIENT_WRITE_TIMEOUT="5s"
CLIENT_MAX_ATTEMPTS=3
CLIENT_RETRY_DELAY="1s"
CLIENT_MAX_RETRY_DELAY="30s"
  
# Logger Configuration
LOG_LEVEL="debug"
LOG_PRETTY=true
LOG_JSON=false