# Server Configuration
SERVER_ADDRESS=":8080"
SERVER_READ_TIMEOUT="5s"
SERVER_WRITE_TIMEOUT="5s"
SERVER_SHUTDOWN_TIMEOUT="10s"
SERVER_MAX_CONNECTIONS=1000
  
# Logger Configuration
LOG_LEVEL="debug"  # debug, info, warn, error, fatal
LOG_PRETTY=true
LOG_JSON=false
  
# PoW Configuration
POW_INITIAL_DIFFICULTY=4
POW_MAX_DIFFICULTY=8
POW_CHALLENGE_TTL="5m"
POW_ADJUST_INTERVAL="10s"